In [ ]:
import torch
import math
import torch.nn.functional as F
    

In [2]:
def scaled_dot_product(q, k, v, mask=None):
    d_k = q.size()[-1]
    attn_logits = torch.matmul(q, k.transpose(-2, -1))
    attn_logits = attn_logits / math.sqrt(d_k)
    if mask is not None:
        attn_logits = attn_logits.masked_fill(mask == 0, -9e15)
    attention = F.softmax(attn_logits, dim=-1)
    values = torch.matmul(attention, v)
    return values, attention

In [3]:
seq_len, d_k = 3, 2
q = torch.randn(seq_len, d_k)
k = torch.randn(seq_len, d_k)
v = torch.randn(seq_len, d_k)
values, attention = scaled_dot_product(q, k, v)
print("Q\n", q)
print("K\n", k)
print("V\n", v)
print("Values\n", values)
print("Attention\n", attention)

Q
 tensor([[-0.3690, -0.1854],
        [-0.5609, -1.3196],
        [ 1.4015,  1.6658]])
K
 tensor([[ 0.5062, -0.3056],
        [ 1.3822,  0.0610],
        [-0.1383, -0.4219]])
V
 tensor([[-1.1839, -2.8667],
        [ 0.7299,  0.9121],
        [-0.9610, -1.0609]])
Values
 tensor([[-0.6031, -1.1655],
        [-0.7483, -1.3383],
        [ 0.2050, -0.0017]])
Attention
 tensor([[0.3379, 0.2562, 0.4059],
        [0.3400, 0.1706, 0.4894],
        [0.1950, 0.7153, 0.0898]])
